# Generated by Django 3.0 on 2021-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0006_feedback_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['is_ads', '-updatedAT']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='experience',
            field=models.CharField(choices=[('positive', 'positive'), ('neutral', 'neutral'), ('negative', 'negative')], max_length=255),
        ),
    ]
